workflows:
  build-price-hawk:
    name: Build Price Hawk APK
    environment:
      flutter: "3.19.6"
      android_signing:
        - keystore_reference: pricehawk_keystore
      vars:
        PACKAGE_NAME: "com.prakhar.pricehawk"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - prakharmishraspn91@gmail.com
