name: price_hawk
description: A price tracking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3

  # Firebase (latest V2 embedding compatible)
  firebase_core: ^3.4.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.2

  # Ads
  google_mobile_ads:  ^5.1.0

  # WebView
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/splash.png


