name: price_hawk
description: A smart price tracker app with multi-language, ads, and notifications.
publish_to: "none" # Private project

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Backend
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.6
  firebase_messaging: ^14.7.10
  http: ^1.2.1

  # Ads
  google_mobile_ads: ^4.0.0

  # State Management
  provider: ^6.1.2

  # UI & Themes
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
   intl: ^0.18.1 

  # Notifications
  flutter_local_notifications: ^17.1.2

  # URL launcher (for donation/contact links)
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

