name: price_hawk
description: A smart price tracking app with premium, ads, donation, and multilingual support.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.0

  # Login options
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^1.14.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^15.0.0

  # Ads
  google_mobile_ads: ^5.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash.png
    - assets/banner_ad.png
    - assets/home.png
    - assets/lang/
