name: price_hawk
description: A smart price tracker app with premium support and ad monetization.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase core & services
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8

  # Google & Facebook login
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # State Management
  provider: ^6.1.2
  package_info_plus: ^6.0.0

  # Ads
  google_mobile_ads: ^4.0.0
  firebase_admob: ^0.11.2+1

  fluttertoast: ^8.2.4
  firebase_analytics: ^10.10.4
  firebase_app_check: ^0.2.1+11
  firebase_storage: ^11.7.4
  http: ^1.2.1
  google_fonts: ^6.1.0
  # Notifications
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.7.20

  # Date formatting
  intl: ^0.18.1

  # Multilingual Support
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3

  # UI & Styling
  lottie: ^3.1.0
  animations: ^2.0.11
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash.png
    - assets/images/
    - assets/lang/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700